from enum import StrEnum


class ListOfferingsIndustryItem(StrEnum):
    AGRICULTURE_AND_AGTECH = "agriculture_and_agtech"
    ALCOHOL_AND_VICE = "alcohol_and_vice"
    ARTIFICIAL_INTELLIGENCE = "artificial_intelligence"
    AR_AND_VR = "ar_and_vr"
    BARS_AND_CLUBS = "bars_and_clubs"
    BEAUTY = "beauty"
    BIOTECH = "biotech"
    BLOCKCHAIN_AND_WEB3 = "blockchain_and_web3"
    BREWERY = "brewery"
    BRICK_AND_MORTAR = "brick_and_mortar"
    CAFE_AND_FOOD_TRUCK = "cafe_and_food_truck"
    CHILDCARE = "childcare"
    CLEAN_TECH = "clean_tech"
    CLIMATE_CHANGE = "climate_change"
    CONSUMER_GOODS = "consumer_goods"
    DEVTOOLS = "devtools"
    DISTILLERY_AND_VINEYARDS = "distillery_and_vineyards"
    EDTECH = "edtech"
    EDUCATION = "education"
    ENERGY = "energy"
    ENTERTAINMENT = "entertainment"
    EVENTS_AND_FESTIVALS = "events_and_festivals"
    FASHION = "fashion"
    FILM = "film"
    FINTECH_AND_FINANCE = "fintech_and_finance"
    FOOD_AND_BEVERAGE = "food_and_beverage"
    FOOD_TECH = "food_tech"
    GAMES = "games"
    HARDWARE = "hardware"
    HEALTHCARE = "healthcare"
    HEALTH_AND_FITNESS = "health_and_fitness"
    HOME_TECH = "home_tech"
    INFRASTRUCTURE_AND_CONSTRUCTION = "infrastructure_and_construction"
    MANUFACTURING = "manufacturing"
    MEDIA = "media"
    MOBILE_APPS = "mobile_apps"
    MOONSHOTS = "moonshots"
    MUSIC = "music"
    PETS = "pets"
    REAL_ESTATE = "real_estate"
    RECREATION = "recreation"
    RESTAURANT = "restaurant"
    ROBOTICS = "robotics"
    SCIENCE_AND_R_AND_D = "science_and_r_and_d"
    SPORTS = "sports"
    SPORTS_TECH = "sports_tech"
    SUSTAINABILITY = "sustainability"
    TECHNOLOGY = "technology"
    TRANSPORTATION = "transportation"
    TRAVEL_AND_TOURISM = "travel_and_tourism"

    def __str__(self) -> str:
        return str(self.value)
